name: Docker Image CI - arm64

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_PLATFORMS: linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          file: Dockerfile.arm64
          cache-from: |
            type=gha .
            type=inline .
            simeononsecurity/docker-mesonnetwork:arm64-cache
            type=registry,ref=simeononsecurity/docker-mesonnetwork:arm64-latest
          cache-to: |
            type=gha .
            type=inline .
            simeononsecurity/docker-mesonnetwork:arm64-cache
            type=registry,ref=simeononsecurity/docker-mesonnetwork:arm64-latest
          tags: simeononsecurity/docker-mesonnetwork:arm64-latest, ghcr.io/simeononsecurity/docker-mesonnetwork:arm64-latest
          github-token: ${{ secrets.PAT_TOKEN }}

          
